### ISSUE TITLE
Waterhole largely (?)  unusable

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/meqtrees#675]
##### at 2009-02-26 13:23:06 Stef Salvini reported:

Waterhole largely (?)  unusable

**Comment by twillis449** [comment]
Can we reopen this issue? I would still like to see a waterhole repository somewhere. Although python scripts might not necessarily work right away, I don't think that any of this stuff came with a guarantee/ Also there is a doc subdirectory with lots of extremely useful presentations by Oleg.
