### ISSUE TITLE
installing meqtrees

### ISSUE THREAD

**Issue by maaijke** [ska-sa/meqtrees#854]
When installing I encountered the following problems:

1. errors when using latest blitz version, so I had to return to blitz0.9. Also, in order to get the right Blitz version used also in MeqNodes I had to add the following line to
MeqNodes/CMakeLists.txt 
INCLUDE_DIRECTORIES(${BLITZ_INCLUDE_DIR})

2. Defining CASACORE_LIBRARY_PATH when running cmake,using -Detc..somehow doesn't work, it went well if I first export it as an environment variable:
export CASACORE_LIBRARY_PATH=/software/users/lofarsoft/software/local/casacore_feb10_2014/lib64/

3.  
#AppAgent/AppUtils  misses path to CASACORE_LIBRARIESwhen trying to link casa_ms:
Linking CXX shared library libapputils.so
/usr/bin/ld: cannot find -lcasa_ms
collect2: ld returned 1 exit status

solve: in AppAgent/AppUtils/CMakeLists.txt  change line:
target_link_libraries(apputils casa_ms)
to:
target_link_libraries(apputils ${CASACORE_LIBRARY_casa_ms})

**Comment by gijzelaerr** [comment]
I think this has been resolved now timba is working with the stock ubuntu blitz.
