### ISSUE TITLE
'trunk' problem (or maybe not - I dunno)

### ISSUE THREAD

**Issue by twillis449** [ska-sa/meqtrees#875]
It looks like there are obscure references to 'trunk' in a few places in the current code. I have a suspicion that may be the reason I seem to need 'trunk' in the path to meqtrees executables.  Isn't trunk a left-over reference to 'svn' or something?

[twillis-HP-EliteBook-8570w 1:46pm] [meqtrees-timba]> tgrep trunk .
./autoconf_share/cvs2cl.pl:          # Special case for following trunk revisions
./autoconf_share/cvs2cl.pl:          if (($branch =~ /^trunk$/i) and ($revision =~ /^[0-9]+.[0-9]+$/))
./autoconf_share/cvs2cl.pl:      # by the tag in parentheses (so trunk or otherwise non-tagged
./autoconf_share/cvs2cl.pl:  \* To follow trunk revisions, use "-F trunk" ("-F TRUNK" also works).
./autoconf_share/cvs2cl.pl:    branch "trunk", right?  Right.
./PyApps/src/Contrib/**init**.py:  print "  $ cd ~; svn co svn://lofar9.astron.nl/var/svn/repos/trunk/Waterhole"
./Tools/Build/dailybuild.sh:export SVN_REPOSITORY="file:///var/svn/repos/trunk/Timba"

**Comment by o-smirnov** [comment]
It is a leftover from svn, but all these references are from old build scripts which have been retired (as well as a largely meaningless print statement). So none of these should be causing your problem. I'm surprised you need "trunk" in path, we certainly don't -- could you elaborate please?

**Comment by twillis449** [comment]
Somewhere deep deep  in my system there is something that wants 'trunk' in the path in order to start the meqserver.  I'll continue to hunt. For the moment I got things to work by just adding a 'trunk' softlink into the system. Anyway, It sounds like its my problem and not yours so I'll close this issue.
